name: cicd

on:
  push:
    branches:
      - "*" # run for branches
    tags:
      - "*" # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2
      - name: unit-test
        run: make unit-test
